name: Test

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: make first-run
      - run: make update-Makefile
      - run: make hello-world
      - run: make date
